import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MonitorSmartphone, ShoppingCart } from 'lucide-react';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Digital Shop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  ads,
}: Readonly<{
  children: React.ReactNode;
  ads: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex flex-col justify-between min-h-screen">
          <header className="fixed z-20 flex items-center justify-between px-20 shadow-xl bg-white w-full h-20">
            <div className="flex items-center gap-3">
              <MonitorSmartphone />
              <Link href="/" className="text-2xl font-bold">
                Digital Shop
              </Link>
            </div>
            <div>
              <ShoppingCart />
            </div>
          </header>
          <div className="mt-20 px-20">{children}</div>
          <div className="my-10 mx-auto flex justify-center">{ads}</div>
          <footer className="w-full flex items-center justify-center h-10 text-white bg-black">
            market
          </footer>
        </main>
      </body>
    </html>
  );
}
